package com.ajdeveloper.instadownloader.Utils;

import android.net.Uri.Builder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class WebTools {
    public static String getFileNameFromUrl(String webAdress) {
        if (!webAdress.isEmpty() && webAdress.startsWith("http")) {
            String name;
            if (webAdress.contains("?")) {
                try {
                    name = webAdress.split("\\?")[0];
                    name = name.substring(name.lastIndexOf("/") + 1);
                    return name.substring(0, name.lastIndexOf("."));
                } catch (Exception e) {
                    e.getMessage();
                }
            } else {
                try {
                    name = webAdress.substring(webAdress.lastIndexOf("/") + 1);
                    return name.substring(0, name.lastIndexOf("."));
                } catch (Exception e2) {
                    e2.getMessage();
                }
            }
        }
        return "";
    }

    public static String getExtensionFromUrl(String webAdress) {
        if (!webAdress.isEmpty() && webAdress.startsWith("http")) {
            String extension;
            if (webAdress.contains("?")) {
                try {
                    extension = webAdress.split("\\?")[0];
                    extension = extension.substring(extension.lastIndexOf("/") + 1);
                    return extension.substring(extension.lastIndexOf("."));
                } catch (Exception e) {
                    e.getMessage();
                }
            } else {
                try {
                    extension = webAdress.substring(webAdress.lastIndexOf("/") + 1);
                    return extension.substring(extension.lastIndexOf("."));
                } catch (Exception e2) {
                    e2.getMessage();
                }
            }
        }
        return "";
    }

    public static String getExtensionFromMimeTypes(String mimtypes) {
        Map<String, String> mime = new HashMap();
        mime.put("application/vnd.hzn-3d-crossword", ".x3d");
        mime.put("video/3gpp2", ".3g2");
        mime.put("application/vnd.mseq", ".mseq");
        mime.put("application/vnd.3m.post-it-notes", ".pwn");
        mime.put("application/vnd.3gpp.pic-bw-large", ".plb");
        mime.put("application/vnd.3gpp.pic-bw-small", ".psb");
        mime.put("application/vnd.3gpp.pic-bw-var", ".pvb");
        mime.put("application/vnd.3gpp2.tcap", ".tcap");
        mime.put("application/x-7z-compressed", ".7z");
        mime.put("application/x-abiword", ".abw");
        mime.put("application/x-ace-compressed", ".ace");
        mime.put("application/vnd.americandynamics.acc", ".acc");
        mime.put("application/vnd.acucobol", ".acu");
        mime.put("application/vnd.acucorp", ".atc");
        mime.put("audio/adpcm", ".adp");
        mime.put("application/x-authorware-bin", ".aab");
        mime.put("application/x-authorware-map", ".aam");
        mime.put("application/x-authorware-seg", ".aas");
        mime.put("application/vnd.adobe.air-application-installer-package+zip", ".air");
        mime.put("application/x-shockwave-flash", ".swf");
        mime.put("application/vnd.adobe.fxp", ".fxp");
        mime.put("application/pdf", ".pdf");
        mime.put("application/vnd.cups-ppd", ".ppd");
        mime.put("application/x-director", ".dir");
        mime.put("application/vnd.adobe.xdp+xml", ".xdp");
        mime.put("application/vnd.adobe.xfdf", ".xfdf");
        mime.put("audio/x-aac", ".aac");
        mime.put("application/vnd.ahead.space", ".ahead");
        mime.put("application/vnd.airzip.filesecure.azf", ".azf");
        mime.put("application/vnd.airzip.filesecure.azs", ".azs");
        mime.put("application/vnd.amazon.ebook", ".azw");
        mime.put("application/vnd.amiga.ami", ".ami");
        mime.put("application/andrew-inset", "N/A");
        mime.put("application/vnd.android.package-archive", ".apk");
        mime.put("application/vnd.anser-code-certificate-issue-initiation", ".cii");
        mime.put("application/vnd.anser-code-funds-transfer-initiation", ".fti");
        mime.put("application/vnd.antix.game-component", ".atx");
        mime.put("application/vnd.apple.installer+xml", ".mpkg");
        mime.put("application/applixware", ".aw");
        mime.put("application/vnd.hhe.lesson-player", ".les");
        mime.put("application/vnd.aristanetworks.swi", ".swi");
        mime.put("text/x-asm", ".s");
        mime.put("application/atomcat+xml", ".atomcat");
        mime.put("application/atomsvc+xml", ".atomsvc");
        mime.put("application/atom+xml", ".atom, .xml");
        mime.put("application/pkix-attr-cert", ".ac");
        mime.put("audio/x-aiff", ".aif");
        mime.put("video/x-msvideo", ".avi");
        mime.put("application/vnd.audiograph", ".aep");
        mime.put("image/vnd.dxf", ".dxf");
        mime.put("model/vnd.dwf", ".dwf");
        mime.put("text/plain-bas", ".par");
        mime.put("application/x-bcpio", ".bcpio");
        mime.put("application/octet-stream", ".bin");
        mime.put("image/bmp", ".bmp");
        mime.put("application/x-bittorrent", ".torrent");
        mime.put("application/vnd.rim.cod", ".cod");
        mime.put("application/vnd.blueice.multipass", ".mpm");
        mime.put("application/vnd.bmi", ".bmi");
        mime.put("application/x-sh", ".sh");
        mime.put("image/prs.btif", ".btif");
        mime.put("application/vnd.businessobjects", ".rep");
        mime.put("application/x-bzip", ".bz");
        mime.put("application/x-bzip2", ".bz2");
        mime.put("application/x-csh", ".csh");
        mime.put("text/x-c", ".c");
        mime.put("application/vnd.chemdraw+xml", ".cdxml");
        mime.put("text/css", ".css");
        mime.put("chemical/x-cdx", ".cdx");
        mime.put("chemical/x-cml", ".cml");
        mime.put("chemical/x-csml", ".csml");
        mime.put("application/vnd.contact.cmsg", ".cdbcmsg");
        mime.put("application/vnd.claymore", ".cla");
        mime.put("application/vnd.clonk.c4group", ".c4g");
        mime.put("image/vnd.dvb.subtitle", ".sub");
        mime.put("application/cdmi-capability", ".cdmia");
        mime.put("application/cdmi-container", ".cdmic");
        mime.put("application/cdmi-domain", ".cdmid");
        mime.put("application/cdmi-object", ".cdmio");
        mime.put("application/cdmi-recycler_queue", ".cdmiq");
        mime.put("application/vnd.cluetrust.cartomobile-config", ".c11amc");
        mime.put("application/vnd.cluetrust.cartomobile-config-pkg", ".c11amz");
        mime.put("image/x-cmu-raster", ".ras");
        mime.put("model/vnd.collada+xml", ".dae");
        mime.put("text/csv", ".csv");
        mime.put("application/mac-compactpro", ".cpt");
        mime.put("application/vnd.wap.wmlc", ".wmlc");
        mime.put("image/cgm", ".cgm");
        mime.put("x-conference/x-cooltalk", ".ice");
        mime.put("image/x-cmx", ".cmx");
        mime.put("application/vnd.xara", ".xar");
        mime.put("application/vnd.cosmocaller", ".cmc");
        mime.put("application/x-cpio", ".cpio");
        mime.put("application/vnd.crick.clicker", ".clkx");
        mime.put("application/vnd.crick.clicker.keyboard", ".clkk");
        mime.put("application/vnd.crick.clicker.palette", ".clkp");
        mime.put("application/vnd.crick.clicker.template", ".clkt");
        mime.put("application/vnd.crick.clicker.wordbank", ".clkw");
        mime.put("application/vnd.criticaltools.wbs+xml", ".wbs");
        mime.put("application/vnd.rig.cryptonote", ".cryptonote");
        mime.put("chemical/x-cif", ".cif");
        mime.put("chemical/x-cmdf", ".cmdf");
        mime.put("application/cu-seeme", ".cu");
        mime.put("application/prs.cww", ".cww");
        mime.put("text/vnd.curl", ".curl");
        mime.put("text/vnd.curl.dcurl", ".dcurl");
        mime.put("text/vnd.curl.mcurl", ".mcurl");
        mime.put("text/vnd.curl.scurl", ".scurl");
        mime.put("application/vnd.curl.car", ".car");
        mime.put("application/vnd.curl.pcurl", ".pcurl");
        mime.put("application/vnd.yellowriver-custom-menu", ".cmp");
        mime.put("application/dssc+der", ".dssc");
        mime.put("application/dssc+xml", ".xdssc");
        mime.put("application/x-debian-package", ".deb");
        mime.put("audio/vnd.dece.audio", ".uva");
        mime.put("image/vnd.dece.graphic", ".uvi");
        mime.put("video/vnd.dece.hd", ".uvh");
        mime.put("video/vnd.dece.mobile", ".uvm");
        mime.put("video/vnd.uvvu.mp4", ".uvu");
        mime.put("video/vnd.dece.pd", ".uvp");
        mime.put("video/vnd.dece.sd", ".uvs");
        mime.put("video/vnd.dece.video", ".uvv");
        mime.put("application/x-dvi", ".dvi");
        mime.put("application/vnd.fdsn.seed", ".seed");
        mime.put("application/x-dtbook+xml", ".dtb");
        mime.put("application/x-dtbresource+xml", ".res");
        mime.put("application/vnd.dvb.ait", ".ait");
        mime.put("application/vnd.dvb.service", ".svc");
        mime.put("audio/vnd.digital-winds", ".eol");
        mime.put("image/vnd.djvu", ".djvu");
        mime.put("application/xml-dtd", ".dtd");
        mime.put("application/vnd.dolby.mlp", ".mlp");
        mime.put("application/x-doom", ".wad");
        mime.put("application/vnd.dpgraph", ".dpg");
        mime.put("audio/vnd.dra", ".dra");
        mime.put("application/vnd.dreamfactory", ".dfac");
        mime.put("image/vnd.dwg", ".dwg");
        mime.put("application/vnd.dynageo", ".geo");
        mime.put("application/ecmascript", ".es");
        mime.put("application/vnd.ecowin.chart", ".mag");
        mime.put("image/vnd.fujixerox.edmics-mmr", ".mmr");
        mime.put("image/vnd.fujixerox.edmics-rlc", ".rlc");
        mime.put("application/exi", ".exi");
        mime.put("application/vnd.proteus.magazine", ".mgz");
        mime.put("application/epub+zip", ".epub");
        mime.put("message/rfc822", ".eml");
        mime.put("application/vnd.enliven", ".nml");
        mime.put("application/vnd.is-xpr", ".xpr");
        mime.put("image/vnd.xiff", ".xif");
        mime.put("application/vnd.xfdl", ".xfdl");
        mime.put("application/emma+xml", ".emma");
        mime.put("application/vnd.ezpix-album", ".ez2");
        mime.put("application/vnd.ezpix-package", ".ez3");
        mime.put("image/vnd.fst", ".fst");
        mime.put("video/vnd.fvt", ".fvt");
        mime.put("image/vnd.fastbidsheet", ".fbs");
        mime.put("application/vnd.denovo.fcselayout-link", ".fe_launch");
        mime.put("video/x-f4v", ".f4v");
        mime.put("video/x-flv", ".flv");
        mime.put("image/vnd.fpx", ".fpx");
        mime.put("image/vnd.net-fpx", ".npx");
        mime.put("text/vnd.fmi.flexstor", ".flx");
        mime.put("video/x-fli", ".fli");
        mime.put("application/vnd.fluxtime.clip", ".ftc");
        mime.put("application/vnd.fdf", ".fdf");
        mime.put("text/x-fortran", ".f");
        mime.put("application/vnd.mif", ".mif");
        mime.put("application/vnd.framemaker", ".fm");
        mime.put("image/x-freehand", ".fh");
        mime.put("application/vnd.fsc.weblaunch", ".fsc");
        mime.put("application/vnd.frogans.fnc", ".fnc");
        mime.put("application/vnd.frogans.ltf", ".ltf");
        mime.put("application/vnd.fujixerox.ddd", ".ddd");
        mime.put("application/vnd.fujixerox.docuworks", ".xdw");
        mime.put("application/vnd.fujixerox.docuworks.binder", ".xbd");
        mime.put("application/vnd.fujitsu.oasys", ".oas");
        mime.put("application/vnd.fujitsu.oasys2", ".oa2");
        mime.put("application/vnd.fujitsu.oasys3", ".oa3");
        mime.put("application/vnd.fujitsu.oasysgp", ".fg5");
        mime.put("application/vnd.fujitsu.oasysprs", ".bh2");
        mime.put("application/x-futuresplash", ".spl");
        mime.put("application/vnd.fuzzysheet", ".fzs");
        mime.put("image/g3fax", ".g3");
        mime.put("application/vnd.gmx", ".gmx");
        mime.put("model/vnd.gtw", ".gtw");
        mime.put("application/vnd.genomatix.tuxedo", ".txd");
        mime.put("application/vnd.geogebra.file", ".ggb");
        mime.put("application/vnd.geogebra.tool", ".ggt");
        mime.put("model/vnd.gdl", ".gdl");
        mime.put("application/vnd.geometry-explorer", ".gex");
        mime.put("application/vnd.geonext", ".gxt");
        mime.put("application/vnd.geoplan", ".g2w");
        mime.put("application/vnd.geospace", ".g3w");
        mime.put("application/x-font-ghostscript", ".gsf");
        mime.put("application/x-font-bdf", ".bdf");
        mime.put("application/x-gtar", ".gtar");
        mime.put("application/x-texinfo", ".texinfo");
        mime.put("application/x-gnumeric", ".gnumeric");
        mime.put("application/vnd.google-earth.kml+xml", ".kml");
        mime.put("application/vnd.google-earth.kmz", ".kmz");
        mime.put("application/vnd.grafeq", ".gqf");
        mime.put("image/gif", ".gif");
        mime.put("text/vnd.graphviz", ".gv");
        mime.put("application/vnd.groove-account", ".gac");
        mime.put("application/vnd.groove-help", ".ghf");
        mime.put("application/vnd.groove-identity-message", ".gim");
        mime.put("application/vnd.groove-injector", ".grv");
        mime.put("application/vnd.groove-tool-message", ".gtm");
        mime.put("application/vnd.groove-tool-template", ".tpl");
        mime.put("application/vnd.groove-vcard", ".vcg");
        mime.put("video/h261", ".h261");
        mime.put("video/h263", ".h263");
        mime.put("video/h264", ".h264");
        mime.put("application/vnd.hp-hpid", ".hpid");
        mime.put("application/vnd.hp-hps", ".hps");
        mime.put("application/x-hdf", ".hdf");
        mime.put("audio/vnd.rip", ".rip");
        mime.put("application/vnd.hbci", ".hbci");
        mime.put("application/vnd.hp-jlyt", ".jlt");
        mime.put("application/vnd.hp-pcl", ".pcl");
        mime.put("application/vnd.hp-hpgl", ".hpgl");
        mime.put("application/vnd.yamaha.hv-script", ".hvs");
        mime.put("application/vnd.yamaha.hv-dic", ".hvd");
        mime.put("application/vnd.yamaha.hv-voice", ".hvp");
        mime.put("application/vnd.hydrostatix.sof-data", ".sfd-hdstx");
        mime.put("application/hyperstudio", ".stk");
        mime.put("application/vnd.hal+xml", ".hal");
        mime.put("application/vnd.ibm.rights-management", ".irm");
        mime.put("application/vnd.ibm.secure-container", ".sc");
        mime.put("text/calendar", ".ics");
        mime.put("application/vnd.iccprofile", ".icc");
        mime.put("image/x-icon", ".ico");
        mime.put("application/vnd.igloader", ".igl");
        mime.put("image/ief", ".ief");
        mime.put("application/vnd.immervision-ivp", ".ivp");
        mime.put("application/vnd.immervision-ivu", ".ivu");
        mime.put("application/reginfo+xml", ".rif");
        mime.put("text/vnd.in3d.3dml", ".3dml");
        mime.put("text/vnd.in3d.spot", ".spot");
        mime.put("model/iges", ".igs");
        mime.put("application/vnd.intergeo", ".i2g");
        mime.put("application/vnd.cinderella", ".cdy");
        mime.put("application/vnd.intercon.formnet", ".xpw");
        mime.put("application/vnd.isac.fcs", ".fcs");
        mime.put("application/ipfix", ".ipfix");
        mime.put("application/pkix-cert", ".cer");
        mime.put("application/pkixcmp", ".pki");
        mime.put("application/pkix-crl", ".crl");
        mime.put("application/pkix-pkipath", ".pkipath");
        mime.put("application/vnd.insors.igm", ".igm");
        mime.put("application/vnd.ipunplugged.rcprofile", ".rcprofile");
        mime.put("application/vnd.irepository.package+xml", ".irp");
        mime.put("text/vnd.sun.j2me.app-descriptor", ".jad");
        mime.put("application/view-archive", ".jar");
        mime.put("application/view-vm", ".class");
        mime.put("application/x-view-jnlp-file", ".jnlp");
        mime.put("application/view-serialized-object", ".ser");
        mime.put("text/x-view-source,view", ".view");
        mime.put("application/javascript", ".js");
        mime.put("application/json", ".json");
        mime.put("application/vnd.joost.joda-archive", ".joda");
        mime.put("video/jpm", ".jpm");
        mime.put("image/jpeg", ".jpeg, .jpg");
        mime.put("image/x-citrix-jpeg", ".jpeg, .jpg");
        mime.put("image/pjpeg", ".pjpeg");
        mime.put("video/jpeg", ".jpgv");
        mime.put("application/vnd.kahootz", ".ktz");
        mime.put("application/vnd.chipnuts.karaoke-mmd", ".mmd");
        mime.put("application/vnd.kde.karbon", ".karbon");
        mime.put("application/vnd.kde.kchart", ".chrt");
        mime.put("application/vnd.kde.kformula", ".kfo");
        mime.put("application/vnd.kde.kivio", ".flw");
        mime.put("application/vnd.kde.kontour", ".kon");
        mime.put("application/vnd.kde.kpresenter", ".kpr");
        mime.put("application/vnd.kde.kspread", ".ksp");
        mime.put("application/vnd.kde.kword", ".kwd");
        mime.put("application/vnd.kenameaapp", ".htke");
        mime.put("application/vnd.kidspiration", ".kia");
        mime.put("application/vnd.kinar", ".kne");
        mime.put("application/vnd.kodak-descriptor", ".sse");
        mime.put("application/vnd.las.las+xml", ".lasxml");
        mime.put("application/x-latex", ".latex");
        mime.put("application/vnd.llamagraphics.life-balance.desktop", ".lbd");
        mime.put("application/vnd.llamagraphics.life-balance.exchange+xml", ".lbe");
        mime.put("application/vnd.jam", ".jam");
        mime.put("application/vnd.lotus-approach", ".apr");
        mime.put("application/vnd.lotus-freelance", ".pre");
        mime.put("application/vnd.lotus-notes", ".nsf");
        mime.put("application/vnd.lotus-organizer", ".org");
        mime.put("application/vnd.lotus-screencam", ".scm");
        mime.put("application/vnd.lotus-wordpro", ".lwp");
        mime.put("audio/vnd.lucent.voice", ".lvp");
        mime.put("audio/x-mpegurl", ".m3u");
        mime.put("video/x-m4v", ".m4v");
        mime.put("application/mac-binhex40", ".hqx");
        mime.put("application/vnd.macports.portpkg", ".portpkg");
        mime.put("application/vnd.osgeo.mapguide.package", ".mgp");
        mime.put("application/marc", ".mrc");
        mime.put("application/marcxml+xml", ".mrcx");
        mime.put("application/mxf", ".mxf");
        mime.put("application/vnd.wolfram.player", ".nbp");
        mime.put("application/mathematica", ".ma");
        mime.put("application/mathml+xml", ".mathml");
        mime.put("application/mbox", ".mbox");
        mime.put("application/vnd.medcalcdata", ".mc1");
        mime.put("application/mediaservercontrol+xml", ".mscml");
        mime.put("application/vnd.mediastation.cdkey", ".cdkey");
        mime.put("application/vnd.mfer", ".mwf");
        mime.put("application/vnd.mfmp", ".mfm");
        mime.put("model/mesh", ".msh");
        mime.put("application/mads+xml", ".mads");
        mime.put("application/mets+xml", ".mets");
        mime.put("application/mods+xml", ".mods");
        mime.put("application/metalink4+xml", ".meta4");
        mime.put("application/vnd.mcd", ".mcd");
        mime.put("application/vnd.micrografx.flo", ".flo");
        mime.put("application/vnd.micrografx.igx", ".igx");
        mime.put("application/vnd.eszigno3+xml", ".es3");
        mime.put("application/x-msaccess", ".mdb");
        mime.put("video/x-ms-asf", ".asf");
        mime.put("application/x-msdownload", ".exe");
        mime.put("application/vnd.ms-artgalry", ".cil");
        mime.put("application/vnd.ms-cab-compressed", ".cab");
        mime.put("application/vnd.ms-ims", ".ims");
        mime.put("application/x-ms-application", ".application");
        mime.put("application/x-msclip", ".clp");
        mime.put("image/vnd.ms-modi", ".mdi");
        mime.put("application/vnd.ms-fontobject", ".eot");
        mime.put("application/vnd.ms-excel", ".xls");
        mime.put("application/vnd.ms-excel.addin.macroenabled.12", ".xlam");
        mime.put("application/vnd.ms-excel.sheet.binary.macroenabled.12", ".xlsb");
        mime.put("application/vnd.ms-excel.template.macroenabled.12", ".xltm");
        mime.put("application/vnd.ms-excel.sheet.macroenabled.12", ".xlsm");
        mime.put("application/vnd.ms-htmlhelp", ".chm");
        mime.put("application/x-mscardfile", ".crd");
        mime.put("application/vnd.ms-lrm", ".lrm");
        mime.put("application/x-msmediaview", ".mvb");
        mime.put("application/x-msmoney", ".mny");
        mime.put("application/vnd.openxmlformats-officedocument.presentationml.presentation", ".pptx");
        mime.put("application/vnd.openxmlformats-officedocument.presentationml.slide", ".sldx");
        mime.put("application/vnd.openxmlformats-officedocument.presentationml.slideshow", ".ppsx");
        mime.put("application/vnd.openxmlformats-officedocument.presentationml.template", ".potx");
        mime.put("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx");
        mime.put("application/vnd.openxmlformats-officedocument.spreadsheetml.template", ".xltx");
        mime.put("application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx");
        mime.put("application/vnd.openxmlformats-officedocument.wordprocessingml.template", ".dotx");
        mime.put("application/x-msbinder", ".obd");
        mime.put("application/vnd.ms-officetheme", ".thmx");
        mime.put("application/onenote", ".onetoc");
        mime.put("audio/vnd.ms-playready.media.pya", ".pya");
        mime.put("video/vnd.ms-playready.media.pyv", ".pyv");
        mime.put("application/vnd.ms-powerpoint", ".ppt");
        mime.put("application/vnd.ms-powerpoint.addin.macroenabled.12", ".ppam");
        mime.put("application/vnd.ms-powerpoint.slide.macroenabled.12", ".sldm");
        mime.put("application/vnd.ms-powerpoint.presentation.macroenabled.12", ".pptm");
        mime.put("application/vnd.ms-powerpoint.slideshow.macroenabled.12", ".ppsm");
        mime.put("application/vnd.ms-powerpoint.template.macroenabled.12", ".potm");
        mime.put("application/vnd.ms-project", ".mpp");
        mime.put("application/x-mspublisher", ".pub");
        mime.put("application/x-msschedule", ".scd");
        mime.put("application/x-silverlight-app", ".xap");
        mime.put("application/vnd.ms-pki.stl", ".stl");
        mime.put("application/vnd.ms-pki.seccat", ".cat");
        mime.put("application/vnd.visio", ".vsd");
        mime.put("application/vnd.visio2013", ".vsdx");
        mime.put("video/x-ms-wm", ".wm");
        mime.put("audio/x-ms-wma", ".wma");
        mime.put("audio/x-ms-wax", ".wax");
        mime.put("video/x-ms-wmx", ".wmx");
        mime.put("application/x-ms-wmd", ".wmd");
        mime.put("application/vnd.ms-wpl", ".wpl");
        mime.put("application/x-ms-wmz", ".wmz");
        mime.put("video/x-ms-wmv", ".wmv");
        mime.put("video/x-ms-wvx", ".wvx");
        mime.put("application/x-msmetafile", ".wmf");
        mime.put("application/x-msterminal", ".trm");
        mime.put("application/msword", ".doc");
        mime.put("application/vnd.ms-word.document.macroenabled.12", ".docm");
        mime.put("application/vnd.ms-word.template.macroenabled.12", ".dotm");
        mime.put("application/x-mswrite", ".wri");
        mime.put("application/vnd.ms-works", ".wps");
        mime.put("application/x-ms-xbap", ".xbap");
        mime.put("application/vnd.ms-xpsdocument", ".xps");
        mime.put("audio/midi", ".mid");
        mime.put("application/vnd.ibm.minipay", ".mpy");
        mime.put("application/vnd.ibm.modcap", ".afp");
        mime.put("application/vnd.jcp.javame.midlet-rms", ".rms");
        mime.put("application/vnd.tmobile-livetv", ".tmo");
        mime.put("application/x-mobipocket-ebook", ".prc");
        mime.put("application/vnd.mobius.mbk", ".mbk");
        mime.put("application/vnd.mobius.dis", ".dis");
        mime.put("application/vnd.mobius.plc", ".plc");
        mime.put("application/vnd.mobius.mqy", ".mqy");
        mime.put("application/vnd.mobius.msl", ".msl");
        mime.put("application/vnd.mobius.txf", ".txf");
        mime.put("application/vnd.mobius.daf", ".daf");
        mime.put("text/vnd.fly", ".fly");
        mime.put("application/vnd.mophun.certificate", ".mpc");
        mime.put("application/vnd.mophun.application", ".mpn");
        mime.put("video/mj2", ".mj2");
        mime.put("video/vnd.mpegurl", ".mxu");
        mime.put("video/mpeg", ".mpeg");
        mime.put("application/mp21", ".m21");
        mime.put("application/vnd.apple.mpegurl", ".m3u8");
        mime.put("application/vnd.musician", ".mus");
        mime.put("application/vnd.muvee.style", ".msty");
        mime.put("application/xv+xml", ".mxml");
        mime.put("application/vnd.nokia.n-gage.data", ".ngdat");
        mime.put("application/vnd.nokia.n-gage.symbian.install", ".n-gage");
        mime.put("application/x-dtbncx+xml", ".ncx");
        mime.put("application/x-netcdf", ".nc");
        mime.put("application/vnd.neurolanguage.nlu", ".nlu");
        mime.put("application/vnd.dna", ".dna");
        mime.put("application/vnd.noblenet-directory", ".nnd");
        mime.put("application/vnd.noblenet-sealer", ".nns");
        mime.put("application/vnd.noblenet-code", ".nnw");
        mime.put("application/vnd.nokia.radio-preset", ".rpst");
        mime.put("application/vnd.nokia.radio-presets", ".rpss");
        mime.put("text/n3", ".n3");
        mime.put("application/vnd.novadigm.edm", ".edm");
        mime.put("application/vnd.novadigm.edx", ".edx");
        mime.put("application/vnd.novadigm.ext", ".ext");
        mime.put("application/vnd.flographit", ".gph");
        mime.put("audio/vnd.nuera.ecelp4800", ".ecelp4800");
        mime.put("audio/vnd.nuera.ecelp7470", ".ecelp7470");
        mime.put("audio/vnd.nuera.ecelp9600", ".ecelp9600");
        mime.put("application/oda", ".oda");
        mime.put("application/ogg", ".ogx");
        mime.put("audio/ogg", ".oga");
        mime.put("video/ogg", ".ogv");
        mime.put("application/vnd.oma.dd2+xml", ".dd2");
        mime.put("application/vnd.oasis.opendocument.text-code", ".oth");
        mime.put("application/oebps-package+xml", ".opf");
        mime.put("application/vnd.intu.qbo", ".qbo");
        mime.put("application/vnd.openofficeorg.extension", ".oxt");
        mime.put("application/vnd.yamaha.openscoreformat", ".osf");
        mime.put("application/vnd.oasis.opendocument.chart", ".odc");
        mime.put("application/vnd.oasis.opendocument.chart-template", ".otc");
        mime.put("application/vnd.oasis.opendocument.database", ".odb");
        mime.put("application/vnd.oasis.opendocument.formula", ".odf");
        mime.put("application/vnd.oasis.opendocument.formula-template", ".odft");
        mime.put("application/vnd.oasis.opendocument.graphics", ".odg");
        mime.put("application/vnd.oasis.opendocument.graphics-template", ".otg");
        mime.put("application/vnd.oasis.opendocument.image", ".odi");
        mime.put("application/vnd.oasis.opendocument.image-template", ".oti");
        mime.put("application/vnd.oasis.opendocument.presentation", ".odp");
        mime.put("application/vnd.oasis.opendocument.presentation-template", ".otp");
        mime.put("application/vnd.oasis.opendocument.spreadsheet", ".ods");
        mime.put("application/vnd.oasis.opendocument.spreadsheet-template", ".ots");
        mime.put("application/vnd.oasis.opendocument.text", ".odt");
        mime.put("application/vnd.oasis.opendocument.text-master", ".odm");
        mime.put("application/vnd.oasis.opendocument.text-template", ".ott");
        mime.put("image/ktx", ".ktx");
        mime.put("application/vnd.sun.xml.calc", ".sxc");
        mime.put("application/vnd.sun.xml.calc.template", ".stc");
        mime.put("application/vnd.sun.xml.draw", ".sxd");
        mime.put("application/vnd.sun.xml.draw.template", ".std");
        mime.put("application/vnd.sun.xml.impress", ".sxi");
        mime.put("application/vnd.sun.xml.impress.template", ".sti");
        mime.put("application/vnd.sun.xml.math", ".sxm");
        mime.put("application/vnd.sun.xml.writer", ".sxw");
        mime.put("application/vnd.sun.xml.writer.global", ".sxg");
        mime.put("application/vnd.sun.xml.writer.template", ".stw");
        mime.put("application/x-font-otf", ".otf");
        mime.put("application/vnd.yamaha.openscoreformat.osfpvg+xml", ".osfpvg");
        mime.put("application/vnd.osgi.dp", ".dp");
        mime.put("application/vnd.palm", ".pdb");
        mime.put("text/x-pascal", ".p");
        mime.put("application/vnd.pawaafile", ".paw");
        mime.put("application/vnd.hp-pclxl", ".pclxl");
        mime.put("application/vnd.picsel", ".efif");
        mime.put("image/x-pcx", ".pcx");
        mime.put("image/vnd.adobe.photoshop", ".psd");
        mime.put("application/pics-rules", ".prf");
        mime.put("image/x-pict", ".pic");
        mime.put("application/x-chat", ".chat");
        mime.put("application/pkcs10", ".p10");
        mime.put("application/x-pkcs12", ".p12");
        mime.put("application/pkcs7-mime", ".p7m");
        mime.put("application/pkcs7-signature", ".p7s");
        mime.put("application/x-pkcs7-certreqresp", ".p7r");
        mime.put("application/x-pkcs7-certificates", ".p7b");
        mime.put("application/pkcs8", ".p8");
        mime.put("application/vnd.pocketlearn", ".plf");
        mime.put("image/x-portable-anymap", ".pnm");
        mime.put("image/x-portable-bitmap", ".pbm");
        mime.put("application/x-font-pcf", ".pcf");
        mime.put("application/font-tdpfr", ".pfr");
        mime.put("application/x-chess-pgn", ".pgn");
        mime.put("image/x-portable-graymap", ".pgm");
        mime.put("image/png", ".png");
        mime.put("image/x-citrix-png", ".png");
        mime.put("image/x-png", ".png");
        mime.put("image/x-portable-pixmap", ".ppm");
        mime.put("application/pskc+xml", ".pskcxml");
        mime.put("application/vnd.ctc-posml", ".pml");
        mime.put("application/postscript", ".ai");
        mime.put("application/x-font-type1", ".pfa");
        mime.put("application/vnd.powerbuilder6", ".pbd");
        mime.put("application/pgp-encrypted", ".pgp");
        mime.put("application/pgp-signature", ".pgp");
        mime.put("application/vnd.previewsystems.box", ".box");
        mime.put("application/vnd.pvi.ptid1", ".ptid");
        mime.put("application/pls+xml", ".pls");
        mime.put("application/vnd.pg.format", ".str");
        mime.put("application/vnd.pg.osasli", ".ei6");
        mime.put("text/prs.lines.tag", ".dsc");
        mime.put("application/x-font-linux-psf", ".psf");
        mime.put("application/vnd.publishare-delta-tree", ".qps");
        mime.put("application/vnd.pmi.widget", ".wg");
        mime.put("application/vnd.quark.quarkxpress", ".qxd");
        mime.put("application/vnd.epson.esf", ".esf");
        mime.put("application/vnd.epson.msf", ".msf");
        mime.put("application/vnd.epson.ssf", ".ssf");
        mime.put("application/vnd.epson.quickanime", ".qam");
        mime.put("application/vnd.intu.qfx", ".qfx");
        mime.put("video/quicktime", ".qt");
        mime.put("application/x-rar-compressed", ".rar");
        mime.put("audio/x-pn-realaudio", ".ram");
        mime.put("audio/x-pn-realaudio-plugin", ".rmp");
        mime.put("application/rsd+xml", ".rsd");
        mime.put("application/vnd.rn-realmedia", ".rm");
        mime.put("application/vnd.realvnc.bed", ".bed");
        mime.put("application/vnd.recordare.musicxml", ".mxl");
        mime.put("application/vnd.recordare.musicxml+xml", ".musicxml");
        mime.put("application/relax-ng-compact-syntax", ".rnc");
        mime.put("application/vnd.data-vision.rdz", ".rdz");
        mime.put("application/rdf+xml", ".rdf");
        mime.put("application/vnd.cloanto.rp9", ".rp9");
        mime.put("application/vnd.jisp", ".jisp");
        mime.put("application/rtf", ".rtf");
        mime.put("text/richtext", ".rtx");
        mime.put("application/vnd.route66.link66+xml", ".link66");
        mime.put("application/rss+xml", ".rss, .xml");
        mime.put("application/shf+xml", ".shf");
        mime.put("application/vnd.sailingtracker.track", ".st");
        mime.put("image/svg+xml", ".svg");
        mime.put("application/vnd.sus-calendar", ".sus");
        mime.put("application/sru+xml", ".sru");
        mime.put("application/set-payment-initiation", ".setpay");
        mime.put("application/set-registration-initiation", ".setreg");
        mime.put("application/vnd.sema", ".sema");
        mime.put("application/vnd.semd", ".semd");
        mime.put("application/vnd.semf", ".semf");
        mime.put("application/vnd.seemail", ".see");
        mime.put("application/x-font-snf", ".snf");
        mime.put("application/scvp-vp-request", ".spq");
        mime.put("application/scvp-vp-response", ".spp");
        mime.put("application/scvp-cv-request", ".scq");
        mime.put("application/scvp-cv-response", ".scs");
        mime.put("application/sdp", ".sdp");
        mime.put("text/x-setext", ".etx");
        mime.put("video/x-sgi-movie", ".movie");
        mime.put("application/vnd.shana.informed.formdata", ".ifm");
        mime.put("application/vnd.shana.informed.formtemplate", ".itp");
        mime.put("application/vnd.shana.informed.interchange", ".iif");
        mime.put("application/vnd.shana.informed.package", ".ipk");
        mime.put("application/thraud+xml", ".tfi");
        mime.put("application/x-shar", ".shar");
        mime.put("image/x-rgb", ".rgb");
        mime.put("application/vnd.epson.salt", ".slt");
        mime.put("application/vnd.accpac.simply.aso", ".aso");
        mime.put("application/vnd.accpac.simply.imp", ".imp");
        mime.put("application/vnd.simtech-mindmapper", ".twd");
        mime.put("application/vnd.commonspace", ".csp");
        mime.put("application/vnd.yamaha.smaf-audio", ".saf");
        mime.put("application/vnd.smaf", ".mmf");
        mime.put("application/vnd.yamaha.smaf-phrase", ".spf");
        mime.put("application/vnd.smart.teacher", ".teacher");
        mime.put("application/vnd.svd", ".svd");
        mime.put("application/sparql-query", ".rq");
        mime.put("application/sparql-results+xml", ".srx");
        mime.put("application/srgs", ".gram");
        mime.put("application/srgs+xml", ".grxml");
        mime.put("application/ssml+xml", ".ssml");
        mime.put("application/vnd.koan", ".skp");
        mime.put("text/sgml", ".sgml");
        mime.put("application/vnd.stardivision.calc", ".sdc");
        mime.put("application/vnd.stardivision.draw", ".sda");
        mime.put("application/vnd.stardivision.impress", ".sdd");
        mime.put("application/vnd.stardivision.math", ".smf");
        mime.put("application/vnd.stardivision.writer", ".sdw");
        mime.put("application/vnd.stardivision.writer-global", ".sgl");
        mime.put("application/vnd.stepmania.stepchart", ".sm");
        mime.put("application/x-stuffit", ".sit");
        mime.put("application/x-stuffitx", ".sitx");
        mime.put("application/vnd.solent.sdkm+xml", ".sdkm");
        mime.put("application/vnd.olpc-sugar", ".xo");
        mime.put("audio/basic", ".au");
        mime.put("application/vnd.wqd", ".wqd");
        mime.put("application/vnd.symbian.install", ".sis");
        mime.put("application/smil+xml", ".smi");
        mime.put("application/vnd.syncml+xml", ".xsm");
        mime.put("application/vnd.syncml.dm+wbxml", ".bdm");
        mime.put("application/vnd.syncml.dm+xml", ".xdm");
        mime.put("application/x-sv4cpio", ".sv4cpio");
        mime.put("application/x-sv4crc", ".sv4crc");
        mime.put("application/sbml+xml", ".sbml");
        mime.put("text/tab-separated-values", ".tsv");
        mime.put("image/tiff", ".tiff");
        mime.put("application/vnd.tao.intent-module-archive", ".tao");
        mime.put("application/x-tar", ".tar");
        mime.put("application/x-tcl", ".tcl");
        mime.put("application/x-tex", ".tex");
        mime.put("application/x-tex-tfm", ".tfm");
        mime.put("application/tei+xml", ".tei");
        mime.put("text/plain", ".txt");
        mime.put("application/vnd.spotfire.dxp", ".dxp");
        mime.put("application/vnd.spotfire.sfs", ".sfs");
        mime.put("application/timestamped-data", ".tsd");
        mime.put("application/vnd.trid.tpt", ".tpt");
        mime.put("application/vnd.triscape.mxs", ".mxs");
        mime.put("text/troff", ".t");
        mime.put("application/vnd.trueapp", ".tra");
        mime.put("application/x-font-ttf", ".ttf");
        mime.put("text/turtle", ".ttl");
        mime.put("application/vnd.umajin", ".umj");
        mime.put("application/vnd.uoml+xml", ".uoml");
        mime.put("application/vnd.unity", ".unityweb");
        mime.put("application/vnd.ufdl", ".ufd");
        mime.put("text/uri-list", ".uri");
        mime.put("application/vnd.uiq.theme", ".utz");
        mime.put("application/x-ustar", ".ustar");
        mime.put("text/x-uuencode", ".uu");
        mime.put("text/x-vcalendar", ".vcs");
        mime.put("text/x-vcard", ".vcf");
        mime.put("application/x-cdlink", ".vcd");
        mime.put("application/vnd.vsf", ".vsf");
        mime.put("model/vrml", ".wrl");
        mime.put("application/vnd.vcx", ".vcx");
        mime.put("model/vnd.mts", ".mts");
        mime.put("model/vnd.vtu", ".vtu");
        mime.put("application/vnd.visionary", ".vis");
        mime.put("video/vnd.vivo", ".viv");
        mime.put("application/ccxml+xml,", ".ccxml");
        mime.put("application/voicexml+xml", ".vxml");
        mime.put("application/x-wais-source", ".src");
        mime.put("application/vnd.wap.wbxml", ".wbxml");
        mime.put("image/vnd.wap.wbmp", ".wbmp");
        mime.put("audio/x-wav", ".wav");
        mime.put("application/davmount+xml", ".davmount");
        mime.put("application/x-font-woff", ".woff");
        mime.put("application/wspolicy+xml", ".wspolicy");
        mime.put("image/webp", ".webp");
        mime.put("application/vnd.webturbo", ".wtb");
        mime.put("application/widget", ".wgt");
        mime.put("application/winhlp", ".hlp");
        mime.put("text/vnd.wap.wml", ".wml");
        mime.put("text/vnd.wap.wmlscript", ".wmls");
        mime.put("application/vnd.wap.wmlscriptc", ".wmlsc");
        mime.put("application/vnd.wordperfect", ".wpd");
        mime.put("application/vnd.wt.stf", ".stf");
        mime.put("application/wsdl+xml", ".wsdl");
        mime.put("image/x-xbitmap", ".xbm");
        mime.put("image/x-xpixmap", ".xpm");
        mime.put("image/x-xwindowdump", ".xwd");
        mime.put("application/x-x509-ca-cert", ".der");
        mime.put("application/x-xfig", ".fig");
        mime.put("application/xhtml+xml", ".xhtml");
        mime.put("application/xml", ".xml");
        mime.put("application/xcap-diff+xml", ".xdf");
        mime.put("application/xenc+xml", ".xenc");
        mime.put("application/patch-ops-error+xml", ".xer");
        mime.put("application/resource-lists+xml", ".rl");
        mime.put("application/rls-services+xml", ".rs");
        mime.put("application/resource-lists-diff+xml", ".rld");
        mime.put("application/xslt+xml", ".xslt");
        mime.put("application/xop+xml", ".xop");
        mime.put("application/x-xpinstall", ".xpi");
        mime.put("application/xspf+xml", ".xspf");
        mime.put("application/vnd.mozilla.xul+xml", ".xul");
        mime.put("chemical/x-xyz", ".xyz");
        mime.put("text/yaml", ".yaml");
        mime.put("application/yang", ".yang");
        mime.put("application/yin+xml", ".yin");
        mime.put("application/vnd.zul", ".zir");
        mime.put("application/zip", ".zip");
        mime.put("application/vnd.handheld-entertainment+xml", ".zmm");
        mime.put("application/vnd.zzazz.deck+xml", ".zaz");
        try {
            return (String) mime.get(mimtypes);
        } catch (Exception e) {
            return "";
        }
    }

    public static String builderURL(String component) {
        String j = Utilities.getRegexBack(component, "(http(s)?:\\/\\/[^\\s\"']+)");
        if (!j.isEmpty()) {
            return j;
        }
        j = Utilities.getRegexBack(component, "([^\\s]+\\.[a-zA-Z]{2,9}/[^\\s]+)");
        if (j.isEmpty()) {
            return "";
        }
        return "http://" + j;
    }

    public static String getUserAgent(String device) {
        ArrayList<String> Mob = new ArrayList();
        Mob.add("Mozilla/5.0 (Linux; Android 5.0; Nexus 5 Build/LPX13D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.102 Mobile Safari/537.36");
        ArrayList<String> Desktop = new ArrayList();
        Desktop.add("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36");
        if (device.toLowerCase().equals("mobile")) {
            return (String) Mob.get(0);
        }
        return (String) Desktop.get(0);
    }

    public static String buildurl(String protocol, String host) {
        Builder buildurl = new Builder();
        buildurl.scheme(protocol).authority(host);
        return buildurl.build().toString();
    }

    public static ArrayList<String> getUrlFromM3U8(String output) {
        ArrayList<String> m3u8 = new ArrayList();
        String[] separate = output.split("\n");
        int p = 0;
        while (p < separate.length) {
            if (!(separate[p].startsWith("#") || separate[p].isEmpty())) {
                m3u8.add(separate[p]);
            }
            p++;
        }
        return m3u8;
    }
}
